version: "3.8"
services:
    nginx:
        build:
            context: ./laravel
            dockerfile: ./docker/laravel-nginx.Dockerfile
        restart: always
        depends_on:
            - php
        ports:
            - "8080:80"
        networks:
            - default

    php:
        build:
            context: .
            dockerfile: ./docker/laravel-php.Dockerfile
        working_dir: /app
        env_file: ./laravel/.env
        restart: always
        expose:
            - "9000"